spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: home
  datasource:
    url: jdbc:postgresql://192.168.1.39:8432/postgres
    username: age
    password: age
    host: 192.168.1.39

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:8432/postgres
    username: age
    password: age
    host: 192.168.0.75

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:8432/postgres
    username: age
    password: age
    host: localhost

---